Use MVVM model for my project
kpira0807/Magic_Answer pull request #7
Opened 2021-11-15 11:25 UTC by kpira0807

Use MVVM model to my project

2021-11-17 13:27 UTC, ios-school-yalantis requested changes
- Заметил  Colors.swift в проекте, лучше добавить Colors.txt OR colors in Assets и использовать SwiftGen (не критично).
- ErrorType это стринг, должен быть `Error` protocol, строки должны быть в Localizable.strings

- Нету вьюМоделей, вся логика построена в моделях, нужно добавить вьМодели, в них вынести всю логику построения данных которая нужна для скрина.

model -> viewModel -> viewController (viewController ничего не знает о model)

- должна быть примерно вот такая древовидная структура в проекте:
-Flows
--Settings
---SettingsModel
---SettingsViewModel
---SettingsViewController
--Answers
---AnswersModel
---AnswersViewModel
---AnswersViewController
-Services
…
-Managers
...
-Resources

2021-11-17 13:27 UTC, ios-school-yalantis commented on MagicAnswer/MagicAnswer/ViewControllers/SettingViewController.swift
> +class SettingViewModel {
replace SettingViewModel in separated file

2021-11-17 13:27 UTC, ios-school-yalantis commented on MagicAnswer/MagicAnswer/ViewControllers/SettingViewController.swift
> +    init?(coder: NSCoder, viewModel: SettingViewModel = SettingViewModel()) {
лучше не использовать дефолтный параметр для контроллера в этом случае, должно быть явно видно чем контроллер проинициализирован вместе создания, так лучше читается код, но не критично.

2021-11-17 13:27 UTC, ios-school-yalantis commented on MagicAnswer/MagicAnswer/ViewControllers/SettingViewController.swift
> +    init(model: SettingModel = SettingModel()){
лучше не использовать дефолтный параметр для viewModel
same issue

2021-11-17 13:27 UTC, ios-school-yalantis commented on MagicAnswer/MagicAnswer/ViewControllers/AnswerViewController.swift
> +        let vc = storyboard.instantiateViewController(identifier: "SettingViewController", creator: {coder -> SettingViewController? in SettingViewController.init(coder: coder, viewModel: SettingView
model -> viewModel -> viewController

проинициализировать все по цепочке!

2021-11-17 13:27 UTC, ios-school-yalantis commented on MagicAnswer/MagicAnswer/SceneDelegate.swift
> +            let vc = storyboard.instantiateViewController(identifier: "AnswerViewController", creator: {coder -> AnswerViewController? in AnswerViewController.init(coder: coder, viewModel: AnswerView
same model -> viewModel -> viewController

2021-11-17 13:27 UTC, ios-school-yalantis commented on MagicAnswer/MagicAnswer/Networks/SettingModel.swift
> +    private func updateAnswer(_ answer: String, for index: Int) {
code in file should look in this sequence

static

let
private let
var 
private var
func 
private func

2021-11-20 20:23 UTC, kpira0807 commented on MagicAnswer/MagicAnswer/ViewControllers/SettingViewController.swift
> +class SettingViewModel {
Спасибо, исправила

2021-11-20 20:23 UTC, kpira0807 commented on MagicAnswer/MagicAnswer/ViewControllers/SettingViewController.swift
> +    init?(coder: NSCoder, viewModel: SettingViewModel = SettingViewModel()) {
Исправила

2021-11-20 20:23 UTC, kpira0807 commented on MagicAnswer/MagicAnswer/ViewControllers/SettingViewController.swift
> +    init(model: SettingModel = SettingModel()){
исправила

2021-11-20 20:23 UTC, kpira0807 commented on MagicAnswer/MagicAnswer/Networks/SettingModel.swift
> +    private func updateAnswer(_ answer: String, for index: Int) {
Исправила

2021-11-21 14:31 UTC, ios-school-yalantis approved these changes
Пересмотрел 
 Все хорошо, все нравится. можно мержить!

2021-11-21 14:50 UTC, merged